### ISSUE TITLE
Error while running process_LA_data.m

### ISSUE THREAD

**Issue by AlKun25** [yzyouzhang/AIR-ASVspoof#14]
Hi, 

Thank you for the repository .
I am trying to run `process_LA_data.m`. I am very new to _MATLAB/OCTAVE_ . 
So I am unable to find a solution for the following problem:
![image](https://user-images.githubusercontent.com/53429438/114871879-602e1000-9e17-11eb-8921-69454d77ef16.png)
 
 I guess this is a silly issue. But I'm unable to find a solution for this

**Comment by yzyouzhang** [comment]
Hi,

Did you try printing the path to the file and check whether the file is there?
By the way, I changed the filename "xxx.cm.train.trn.txt" to "xxx.cm.train.trl.txt". to make it consistent with dev and eval. Maybe this could cause that the textscan cannot find your training protocol.
Hope this helps. Feel free to ask follow-up questions.

**Comment by AlKun25** [comment]
I tried making it consistent with the _eval_ and _dev_  _protocol_ files and it worked perfectly.

**Comment by AlKun25** [comment]
@yzyouzhang I have noticed one more thing that there is an _end_ statement missing after the _for_ loop for **extracting features for train data** . 
It was causing my code to only process a single _training_ audio file.

**Comment by yzyouzhang** [comment]
Good catch! Thanks! I may have accidentally deleted it by mistake.

**Comment by BrutalCaeser** [comment]
Hi I am also facing the same issue. It's in line 23 
Error using textscan
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in process_LA_data (line 23)
trainprotocol = textscan(trainfileID, '%s%s%s%s%s');

**Comment by SuchitReddi** [comment]
@BrutalCaeser Using fopen instead of textscan is generating error for me. Actually, textscan is working fine.
