### ISSUE TITLE
Can you apply your code for feature embedding visualization? 

### ISSUE THREAD

**Issue by kabrate** [yzyouzhang/AIR-ASVspoof#16]
Does a  point mean an audio file in the plot? I met some problems in drawing the feature embedding visualization.

**Comment by yzyouzhang** [comment]
Thanks for your interest in our work. 
Each point corresponds to the embedding of the speech feature of one audio file. We used tSNE visualization. Could you explain more about the problems you encounter?

**Comment by kabrate** [comment]
I find a code in https://musicinformationretrieval.com/pca.html. In this code, one audio file can genetate numerous points.It seems that the feature vector of one frame can generate a  point. It confused me.

**Comment by yzyouzhang** [comment]
In our work, we first extract LFCC features for audio files. We then feed the LFCC feature to the deep network and output the embedding. What we visualized in our paper is the dimensionally reduced embedding.

**Comment by kabrate** [comment]
Thang you for your reply! I found out what the problem was.
