### ISSUE TITLE
how to get cm_scores for eval set when labels are not present

### ISSUE THREAD

**Issue by rohit18115** [yzyouzhang/AIR-ASVspoof#17]
hey, 

Thanks for the repository!
I'm trying to test the model with ocsoftmax loss on a test set which do not contains labels but to surprise in the file test.py also labels are being used, which makes it impossible to calculate CM scores without the use of labels at least when using ocsoftmax or amsoftmax loss. Am I missing something? Please be patient and gentle. I have just started working on this topic. 

Hope you reply soon.
Thanks

Here is a snapshot of the test.py for your reference. 
![Screenshot from 2021-06-02 20-06-37](https://user-images.githubusercontent.com/44645684/120499924-13f65980-c3de-11eb-8e30-807b63e18302.png)

**Comment by rohit18115** [comment]
ohhh okay, thank you so much for such a fast response. Now I get it. 
And if I may ask, are you participating in ASVspoof 2021? It would be great if you could provide some guidance regarding that. 
A maid id or any other way to contact you to discuss it further would be great.

Thanks in Advance

**Comment by yzyouzhang** [comment]
Please reach out to yzyouzhang@gmail.com regarding that. I will close this issue for now. Thanks.
