### ISSUE TITLE
ohhh okay, thank you so much for such a fast response. Now I get it.

### ISSUE THREAD

**Issue by beijita-yegucheng** [yzyouzhang/AIR-ASVspoof#18]
ohhh okay, thank you so much for such a fast response. Now I get it. 
And if I may ask, are you participating in ASVspoof 2021? It would be great if you could provide some guidance regarding that. 
A maid id or any other way to contact you to discuss it further would be great.

Thanks in Advance

_Originally posted by @rohit18115 in https://github.com/yzyouzhang/AIR-ASVspoof/issues/17#issuecomment-853127084_

**Comment by beijita-yegucheng** [comment]
hey,

Thanks for the repository!
I'm trying to test the model with ocsoftmax loss on a test set which do not contains labels but to surprise in the file test.py also labels are being used, which makes it impossible to calculate CM scores without the use of labels at least when using ocsoftmax or amsoftmax loss. Am I missing something? Please be patient and gentle. I have just started working on this topic.


Excuse me, how did you solve the above problem? I am also struggling with this problem. I hope you can give me the correct answer. Thank you very much!

**Comment by rohit18115** [comment]
hey, @beijita-yegucheng if you look at the code of ocsoftmax in loss.py you would realize that the score calculation does not need labels. So what I did was, I fed garbage or random values as labels(and did not make any change in the original code) and only picked up the scores and did not consider the loss part. And I think this is what the author @yzyouzhang also explained in the issue that I raised. 

Hope this helps :)

**Comment by beijita-yegucheng** [comment]
Thank you very much for your quick reply. Your solution is very good and I have considered it. But can you send me a copy of the specific code? Thank you very much.

**Comment by rohit18115** [comment]
hahaha, sorry I can't do that, I have made quite a lot of changes to it. But I think its not that difficult to get the CM scores using the methodology described above. Please do the needful. 

Thanks

**Comment by yzyouzhang** [comment]
I agree with @rohit18115. Thanks!
