### ISSUE TITLE
I can't fine 'extract_lfcc' function in  process_LA_data.m

### ISSUE THREAD

**Issue by hongchengzhu** [yzyouzhang/AIR-ASVspoof#20]
![QQ截图20210927153503](https://user-images.githubusercontent.com/80734139/134864331-90abcb0b-a74b-45bb-ad52-351597ea0082.png)

Thanks for your good work and open code access. I'd like to run your code, but find there is no function definition of extract_lfcc.
Could you update the code? Thanks very much.

**Comment by yzyouzhang** [comment]
Thanks for your question! We used the LFCC extraction code from https://www.asvspoof.org/index2019.html. You can also find a new PyTorch version of the feature extraction in our recent work https://github.com/yzyouzhang/Empirical-Channel-CM, where we borrowed some code from https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts. I'll update the code in the near future, but you can try the above resources. Please let me know if you have further questions. Thanks.

**Comment by hongchengzhu** [comment]
> Thanks for your question! We used the LFCC extraction code from https://www.asvspoof.org/index2019.html. You can also find a new PyTorch version of the feature extraction in our recent work https://github.com/yzyouzhang/Empirical-Channel-CM, where we borrowed some code from https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts. I'll update the code in the near future, but you can try the above resources. Please let me know if you have further questions. Thanks.

Thank you very much. The problem has been solved. Wish you a good day.
