### ISSUE TITLE
Hi， what is the meaning of “class SelfAttention(nn.Module)” in resnet.py ?!

### ISSUE THREAD

**Issue by JJ-Guo1996** [yzyouzhang/AIR-ASVspoof#25]

**Comment by yzyouzhang** [comment]
Hi,

Thanks for your question. The self-attention is for attentive pooling across time frames. Details can be found in Sect. 3.2 of the reference below.
J. Monteiro, J. Alam, and T. H. Falk, “Generalized end-to-end detection of spoofing attacks to automatic speaker recognizers,” Computer Speech & Language, p. 101096, 2020.
