### ISSUE TITLE
MATLAB process_LA_data error

### ISSUE THREAD

**Issue by BrutalCaeser** [yzyouzhang/AIR-ASVspoof#27]
I tried running the LA data file but it gives error 
Error using textscan
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in process_LA_data (line 23)
trainprotocol = textscan(trainfileID, '%s%s%s%s%s');

I am new at matlab and this seems like a stupid error. Kindly help me on this.

**Comment by yzyouzhang** [comment]
Thanks for your question. Did you try printing the path to the file and check whether the file is there?
I changed the filename "xxx.cm.train.trn.txt" to "xxx.cm.train.trl.txt". to make it consistent with dev and eval. Maybe this could cause that the textscan cannot find your training protocol.
If you prefer a python version of feature extraction, please refer to `preprocess.py` in our new repo for the follow-up work https://github.com/yzyouzhang/Empirical-Channel-CM. 
Thanks.
