### ISSUE TITLE
老哥，你好！

### ISSUE THREAD

**Issue by JJ-Guo1996** [yzyouzhang/AIR-ASVspoof#30]
老哥，你好！我看asvspoof2019数据集中的真实语音和伪造语音数量是失衡的，是否考虑过model检测会倾向于spoof？提出的one-class损失函数是针对这种数据失衡的吗？还是说对于均衡数据集也可以达到不错的效果？另外，我看到ASVspoof2019.LA.cm.train.trl.txt文件中，首先是真实样本然后是伪造样本，在model训练过程中并没有shuffle数据，这也是有意为之吗？

**Comment by yzyouzhang** [comment]
我们用的EER做evaluation，而不是accuracy，所以不太会受到数据失衡的影响。我model训练过程中dataloader是shuffle过的。
https://github.com/yzyouzhang/AIR-ASVspoof/blob/master/train.py#L121

**Comment by yzyouzhang** [comment]
提出的one-class损失函数是针对attack的泛化性，不是对数据失衡

**Comment by JJ-Guo1996** [comment]
我观察到同样的数据，同样的模型参数，但是训出来的结果两次EER相差0.5左右，（设置了固定的随机种子）

**Comment by yzyouzhang** [comment]
你是指不同的随机数种子吗？确实有这个问题，很多文章也指出了这个问题

https://arxiv.org/abs/2103.11326

https://ieeexplore.ieee.org/abstract/document/9747766

我觉得可能是这个数据集和大部分machine learning的数据集不太一样，eval和training分布不同，很难根据dev去判断过拟合。而且数据集比较小，所以结果的波动是正常的
