### ISSUE TITLE
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by MiPlayer123** [yzyouzhang/AIR-ASVspoof#31]
Hi. I am running into the following error. I am wondering if you can help me.
```
Traceback (most recent call last):
  File "[path]/AIR-ASVspoof/dataset.py", line 53, in __getitem__
    feat_mat = pickle.load(feature_handle)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[path]/AIR-ASVspoof/train.py", line 265, in <module>
    _, _ = train(args)
  File "[path]/Mikul/AIR-ASVspoof/train.py", line 126, in train
    feat, _, _, _ = training_set[29]
  File "[path]/AIR-ASVspoof/dataset.py", line 61, in __getitem__
    feat_mat = pickle.load(feature_handle)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```
Thanks

**Comment by yzyouzhang** [comment]
It seems that the data you are trying to load with pickle has a different data structure. Please refer to https://stackoverflow.com/questions/25151206/python-cpickle-load-fails-with-unpicklingerror
Did you run my [reload.py](https://github.com/yzyouzhang/AIR-ASVspoof/blob/master/reload_data.py)?
Also, please check the version of pickle and numpy you are using. I am not sure if version difference will cause issues.

**Comment by MiPlayer123** [comment]
I have not, that might be it. I will try that and update here.

**Comment by MiPlayer123** [comment]
Thank you, issue resolved; it was due to reload.py not running
