### ISSUE TITLE
how to do Feature embedding visualization?

### ISSUE THREAD

**Issue by ZigHello** [yzyouzhang/AIR-ASVspoof#33]
hi，author！I noticed the feature visualization in Figure 2 in the paper, I would like to ask for the plotting details here, is it convenient to provide some plotting source code to help?

**Comment by yzyouzhang** [comment]
Hi,
Please reach out to my email. I can send the Jupyter notebook to you.

**Comment by hashim19** [comment]
Hi, 
thanks for the amazing work. Can you also share the jupyter notebook with me? I am also looking to visualize the feature embeddings.
