### ISSUE TITLE
Minor code errors in process_LA_data.m

### ISSUE THREAD

**Issue by SuchitReddi** [yzyouzhang/AIR-ASVspoof#34]
I don't have much experience with Matlab, so there may be a few mistakes. I apologize for this in advance.

**Desired folder not formed**
Line 14: pathToFeatures = horzcat('/home/yzh298/anti-spoofing/ASVspoof2019', access_type, 'Features/');
Add / after ASVspoof2019 and before Features to make them into different folders; the above code results in a folder named 'ASVspoof2019LAFeatures'. 
Fix: After adding /'s, the code becomes;
pathToFeatures = horzcat('/home/yzh298/anti-spoofing/ASVspoof2019/', access_type, '/Features/');
and the resulting path will be ASVspoof2019/LA/Features.

**Incorrect file name**
Line 17: trainProtocolFile = fullfile(pathToDatabase, horzcat('ASVspoof2019_', access_type, '_cm_protocols'), horzcat('ASVspoof2019.', access_type, '.cm.train.trl.txt'));
Here, the last part of the path has '.cm.train.trl.txt'. The original dataset folder 'DS_10283_3336' has a file named ASVspoof2019.LA.com.train.tr**n**.txt in the above path. So the code displays a ' file not found ' error.
Fix: Replace the trl in the file name with trn.

**Comment by yzyouzhang** [comment]
Thank you! 
For the desired folder, I made the folder in advance on my machine. 
For the incorrect filename, thank you for pointing that out. I manually changed it for my own convenience previously.

**Comment by SuchitReddi** [comment]
Thank you for the repository! It was a huge help. I am currently working on this for my university project.

**Comment by yzyouzhang** [comment]
Glad to hear that!
If you would like a pure Python version, please refer to https://github.com/yzyouzhang/Empirical-Channel-CM for `feature_extraction.py`.
Wish you all the best on your project!

**Comment by SuchitReddi** [comment]
Our project requires both python and MATLAB, luckily. But I will look into the pure python version. Thank you!
