### ISSUE TITLE
750帧的训练？

### ISSUE THREAD

**Issue by JJ-Guo1996** [yzyouzhang/AIR-ASVspoof#41]
哈喽啊，请问尝试过其它帧的训练策略吗？比如300帧或者500帧，效果如何呢？

**Comment by yzyouzhang** [comment]
尝试过一点 效果没有750好 但是也不一定750就是最好，这些参数可以在train.py的argument里面调

**Comment by JJ-Guo1996** [comment]
> 尝试过一点 效果没有750好 但是也不一定750就是最好，这些参数可以在train.py的argument里面调

尝试过300吗？感觉asvspoof数据集都是短时间语音，设置为750，会增加更多的padding数据，导致模型泛化性不太好～

**Comment by yzyouzhang** [comment]
你可以plot一下数据集的时间长度分布，750帧及以下能cover大部分数据，确实多数为短时。但是仅用短时训练效果不是最佳，可能切的时候戛然而止也会带来新的影响

**Comment by JJ-Guo1996** [comment]
> 你可以plot一下数据集的时间长度分布，750帧及以下能cover大部分数据，确实多数为短时。但是仅用短时训练效果不是最佳，可能切的时候戛然而止也会带来新的影响
是的，plot后数据集中的数据都没有超过2s，750帧应该是7.5s吧？
