### ISSUE TITLE
对比实验部分的的resnet+ocsvm，resnet是预训练好freeze的么，还是可以参与训练的？

### ISSUE THREAD

**Issue by flatblackwhite** [yzyouzhang/AIR-ASVspoof#44]

**Comment by yzyouzhang** [comment]
是先用binary classification训练好freeze的，然后只拿最后一层的embedding来训ocsvm

**Comment by flatblackwhite** [comment]
one classification任务怎么得到binary classification的数据呢

**Comment by yzyouzhang** [comment]
原数据集里两类的数据都有，我们用的one-class定义来自"A survey of recent trends in one class classification"
