### ISSUE TITLE
Loading Resnet-18 in GPU memory is taking a long time. 

### ISSUE THREAD

**Issue by bekoju** [yzyouzhang/AIR-ASVspoof#45]
I have been stuck in these steps for a long time. Is this due to the large model size? 

https://github.com/yzyouzhang/AIR-ASVspoof/blob/f3df466f6a68433fd9238dd4117c411d6f3aff8c/train.py#L110

In addition, The default number of workers is 0.  What is it's effect? 

https://github.com/yzyouzhang/AIR-ASVspoof/blob/f3df466f6a68433fd9238dd4117c411d6f3aff8c/train.py#L45

**Comment by yzyouzhang** [comment]
I don't think the model size is large. Are you loading it on CPU or GPU?
num_workers=0 means only the main process will load batches.

**Comment by bekoju** [comment]
The problem is solved when I used the current version of PyTorch.

**Comment by yzyouzhang** [comment]
Thank you! Feel free to ask more questions.
